-- MySQL Script generated by MySQL Workbench
-- Mon Jan 22 09:07:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz2` ;
USE `quiz2` ;

-- -----------------------------------------------------
-- Table `quiz2`.`QUIZ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`QUIZ` (
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`quiz_id`),
  UNIQUE INDEX `quiz_id_UNIQUE` (`quiz_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`QUESTION` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_text` VARCHAR(255) NOT NULL,
  `option_a` VARCHAR(255) NOT NULL,
  `option_b` VARCHAR(255) NOT NULL,
  `option_c` VARCHAR(255) NOT NULL,
  `option_d` VARCHAR(255) NOT NULL,
  `correct_option` VARCHAR(1) NOT NULL,
  `QUIZ_quiz_id` INT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_QUESTION_QUIZ_idx` (`QUIZ_quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTION_QUIZ`
    FOREIGN KEY (`QUIZ_quiz_id`)
    REFERENCES `quiz2`.`QUIZ` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
